name: Check Sensitive Files


on:
  pull_request:
    branches: [main]
    
jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # importante para comparar con el base

      - name: Get changed files
        id: changed-files
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD > changed.txt
          cat changed.txt

      - name: Check for sensitive files
        run: |
          SENSITIVE_FILES=(".github/workflows/protections.yml" ".github/workflows/pull_requests.yml")
          for file in "${SENSITIVE_FILES[@]}"; do
            if grep -q "^$file$" changed.txt; then
              echo "❌ Sensitive file modified: $file"
              exit 1
            fi
          done
          echo "✅ No sensitive files modified"
