name: Check Sensitive Files


on:
  pull_request:
    branches: [main]
    
jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # importante para comparar con el base

      - name: Get changed files
        id: changed-files
        run: |
          echo lol