name: Verificar revisión de usuario específico

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, review_requested, ready_for_review]

jobs:
  check-reviewer:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Obtener revisiones del PR
        id: reviews
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validar aprobación de usuario específico
        run: |
          echo "${{ steps.reviews.outputs.data }}" > reviews.json
          if jq -e '.[] | select(.user.login == "usuario-revisor" and .state == "APPROVED")' reviews.json > /dev/null; then
            echo "El PR fue aprobado por usuario-revisor."
          else
            echo "❌ El PR no ha sido aprobado por usuario-revisor. Falla el job."
            exit 1
          fi
