name: Check PR Reviewer

on:
  pull_request_review:
    types: [submitted]
    branches:
      - main


jobs:
  check-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if reviewer is not elkofix
        run: |
          echo "Review submitted by: ${{ github.actor }}"
          if [[ "${{ github.actor }}" != "elkofix" ]]; then
            echo "Only 'elkofix' can submit PR reviews. Failing."
            exit 1
          else
            echo "Review is from 'elkofix'. All good."
          fi
